# Netlify Configuration for Vite + React SPA
# Critical: Files in public/ folder MUST be copied to dist/ during build

[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600"

# SPA routing for React Router
# Netlify's "shadowing" ensures existing files (sitemap.xml, robots.txt) 
# are served directly and NOT rewritten to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
