// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxgkwoaglxanmgotqvdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4Z2t3b2FnbHhhbm1nb3RxdmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODU3MjIsImV4cCI6MjA3MDc2MTcyMn0.yLU-OqCKat--DGzIMQ4lv3ur-WD0NfUTAfpyeciU4HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});